ProductTrackingSystem/Controllers/ProductController.cs
using Business.Concrete;
using DataAccess.EntityFramework;
using ProductTrackingSystem.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace ProductTrackingSystem.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager(new EfProductDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index(int p = 1)
        {
            var productValues = pm.GetAll().ToPagedList(p, 4);
            return View(productValues);
        }

        public ActionResult ProductReport()
        {
            var productValues = pm.GetAll();
            return View(productValues);
        }

        [HttpGet]
        public ActionResult AddProduct()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.vc = valueCategory;
            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(Product product)
        {
            product.Date = DateTime.Parse(DateTime.Now.ToShortDateString());
            pm.Add(product);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditProduct(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.vc = valueCategory;
            var productValue = pm.GetById(id);
            return View(productValue);
        }
        [HttpPost]
        public ActionResult EditProduct(Product product)
        {
            pm.Update(product);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteProduct(int id)
        {
            var productValue = pm.GetById(id);
            //productValue.ProductStatus=false
            pm.Delete(productValue);
            return RedirectToAction("Index");
        }
    }
}

ProductTrackingSystem/Controllers/UserPanelController.cs
using Business.Concrete;
using Business.ValidationRules.FluentValidation;
using DataAccess.EntityFramework;
using FluentValidation.Results;
using ProductTrackingSystem.DataAccess;
using ProductTrackingSystem.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductTrackingSystem.Controllers
{
    public class UserPanelController : Controller
    {
        ProductManager pm = new ProductManager(new EfProductDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        UserManager um = new UserManager(new EfUserDal());
        ProductTrackingDbContext c = new ProductTrackingDbContext();
        UserValidator userValidator = new UserValidator();

        [HttpGet]
        public ActionResult UserProfile(int id=0)
        {
            string p = (string)Session["Email"];
            id = c.Users.Where(x => x.Email == p).Select(y => y.UserId).FirstOrDefault();
            var userValues = um.GetById(id);
            return View(userValues);
        }
        [HttpPost]
        public ActionResult UserProfile(User user)
        {
            ValidationResult results = userValidator.Validate(user);
            if (results.IsValid)
            {
                um.Update(user);
                return RedirectToAction("UserProfile");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult MyProduct()
        {
            var values = pm.GetAll();
            return View(values);
        }

        [HttpGet]
        public ActionResult NewProduct()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.vc = valueCategory;
            return View();
        }
        [HttpPost]
        public ActionResult NewProduct(Product product)
        {
            product.Date = DateTime.Parse(DateTime.Now.ToShortDateString());
            pm.Add(product);
            return RedirectToAction("MyProduct");
        }

        [HttpGet]
        public ActionResult EditProduct(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.vc = valueCategory;
            var productValue = pm.GetById(id);
            return View(productValue);
        }
        [HttpPost]
        public ActionResult EditProduct(Product product)
        {
            pm.Update(product);
            return RedirectToAction("MyProduct");
        }

        public ActionResult DeleteProduct(int id)
        {
            var productValue = pm.GetById(id);
            //productValue.ProductStatus=false
            pm.Delete(productValue);
            return RedirectToAction("MyProduct");
        }
    }
}

ProductTrackingSystem/Views/UserPanel/EditProduct.cshtml
@model ProductTrackingSystem.Entities.Concrete.Product

@{
    ViewBag.Title = "EditProduct";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Ürün Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditProduct", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.ProductId, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Adı")
        @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control" })
        <br />
        @Html.Label("Stok Miktarı")
        @Html.TextBoxFor(x => x.UnitsInStock, new { @class = "form-control" })
        <br />
        @Html.Label("Birim Fiyatı")
        @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

ProductTrackingSystem/Views/UserPanel/MyProduct.cshtml
@using ProductTrackingSystem.Entities.Concrete
@model List<Product>

@{
    ViewBag.Title = "MyProduct";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@{ string color = "";}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 15%">
                                Ürün Adı
                            </th>
                            <th style="width: 15%">
                                Stok Miktarı
                            </th>
                            <th style="width: 15%">
                                Birim Fiyatı
                            </th>
                            <th style="width: 15%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 15%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Beyaz Eşya")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Küçük Ev Aletleri")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Mutfak Eşyaları")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Teknolojik Aletler")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Mobilya")
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                                <td>
                                    @item.ProductId
                                </td>
                                <td>
                                    <a>
                                        @item.ProductName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.Date).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    @item.UnitsInStock
                                </td>
                                <td>
                                    @item.UnitPrice
                                </td>
                                @*<td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <img alt="Avatar" class="table-avatar" src="">

                                            </li>
                                        </ul>
                                    </td>*@
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Comment/CommentByProduct/@item.ProductId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yorumlar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/UserPanel/EditProduct/@item.ProductId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/UserPanel/DeleteProduct/@item.ProductId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>
</html>
<a href="/UserPanel/NewProduct/" class="btn btn-primary">Yeni Ürün Girişi</a>

ProductTrackingSystem/Views/UserPanel/NewProduct.cshtml
@model ProductTrackingSystem.Entities.Concrete.Product

@{
    ViewBag.Title = "NewProduct";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Yeni Ürün Ekleme Sayfası</h2>
<br />
@using (Html.BeginForm("AddProduct", "Product", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Ürün Adı")
        @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProductName)
        <br />
        @Html.Label("Stok Miktarı")
        @Html.TextBoxFor(x => x.UnitsInStock, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.UnitsInStock)
        <br />
        @Html.Label("Birim Fiyatı")
        @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.UnitPrice)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />
        <button class="btn btn-info">Ürün Ekle</button>
    </div>
}

ProductTrackingSystem/Views/UserPanel/UserProfile.cshtml
@model ProductTrackingSystem.Entities.Concrete.User

@{
    ViewBag.Title = "UserProfile";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Profilinizi Düzenleyin</h2>
@using (Html.BeginForm("UserProfile", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @*@Html.Label("ID")*@
        @Html.HiddenFor(x => x.UserId, new { @class = "form-control" })

        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name)
        <br />
        @Html.Label("Kullanıcı Soyadı")
        @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Surname)
        <br />
        @Html.Label("Email")
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Email)
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Password)
        <br />
        @Html.Label("Hakkında")
        @Html.TextBoxFor(x => x.About, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.About)
        <br />
        <button class="btn btn-success">Profili Güncelle</button>
    </div>
}